#pragma once
#define NUM_SIDES 2
#define WHITE 0
#define BLACK 1

#define BOARD_SIDE_LENGTH 8
#define NUM_SQUARES (BOARD_SIDE_LENGTH * BOARD_SIDE_LENGTH)
#define NUM_PAWN_SQUARES (NUM_SQUARES - NUM_SIDES * BOARD_SIDE_LENGTH)

#define ENPASSANT_ROW_0INDEX 3
#define KING_HOME_COLUMN_0INDEX 3

#define NUM_PIECE_TYPES 5
#define BISHOP 0
#define NUM_BASE_BISHOPS_PSIDE 2
#define KNIGHT 1
#define NUM_BASE_KNIGHTS_PSIDE 2
#define ROOK 2
#define NUM_BASE_ROOKS_PSIDE 2
#define QUEEN 3
#define NUM_BASE_QUEENS_PSIDE 1
#define KING 4
#define NUM_KINGS_PSIDE 1
#define NUM_PIECE_TYPES_LESS_KING (NUM_PIECE_TYPES - NUM_KINGS_PSIDE)
#define NUM_BASE_CAPTURABLE_PIECES_PSIDE (BOARD_SIDE_LENGTH - NUM_KINGS_PSIDE)

#define NUM_PAWNS_PSIDE BOARD_SIDE_LENGTH
#define MAX_PROMOTIONS_PSIDE NUM_PAWNS_PSIDE

#define NUM_CHESSMEN_PSIDE (NUM_PAWNS_PSIDE + NUM_PIECES_PSIDE)
#define NUM_CHESSMEN_PSIDE_LESS_KING (NUM_CHESSMEN_PSIDE - NUM_KINGS_PSIDE)
#define MAX_PIECES_PSIDE_LESS_KING NUM_CHESSMEN_PSIDE_LESS_KING

#define NUM_PIECES_PSIDE BOARD_SIDE_LENGTH
#define NUM_PIECES_PSIDE_LESS_KING (NUM_PIECES_PSIDE - NUM_KINGS_PSIDE)

#define MAX_BISHOPS_PSIDE (NUM_BASE_BISHOPS_PSIDE + MAX_PROMOTIONS_PSIDE)
#define MAX_KNIGHTS_PSIDE (NUM_BASE_KNIGHTS_PSIDE + MAX_PROMOTIONS_PSIDE)
#define MAX_ROOKS_PSIDE (NUM_BASE_ROOKS_PSIDE + MAX_PROMOTIONS_PSIDE)
#define MAX_QUEENS_PSIDE (NUM_BASE_QUEENS_PSIDE + MAX_PROMOTIONS_PSIDE)

#define NUM_FIXED_ROOK_SCENARIOS 3
extern int BASE_PIECES[NUM_FIXED_ROOK_SCENARIOS][NUM_PIECE_TYPES_LESS_KING];
