#include "position.h"

// NOTE: should add test, sum to -1
#define WHITE_SQ_MASK 0xAA55AA55AA55AA55
#define BLACK_SQ_MASK 0x55AA55AA55AA55AA

enum PROMOTION_ERROR_CODES {
  SIDE0_MORE_PROMOTIONS_THAN_MISSING_PAWNS = 1,
  SIDE1_MORE_PROMOTIONS_THAN_MISSING_PAWNS, // 2
  SIDE0_ALLOWS_LESS_THAN_TOTAL_PROMOTIONS,  // 3
  SIDE1_ALLOWS_LESS_THAN_TOTAL_PROMOTIONS   // 4
};

char validate_num_promotions(position p);
